// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nk2QHziQZu-BQ0kupiG6Z-2ce4XbiNA',
    appId: '1:868959012606:web:dac67eefa4ddc15a8c87af',
    messagingSenderId: '868959012606',
    projectId: 'jaldi-app-cb1',
    authDomain: 'jaldi-app-cb1.firebaseapp.com',
    storageBucket: 'jaldi-app-cb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlBMEMYWxiE0RBWX36sWQXcdmUgdAE6vM',
    appId: '1:868959012606:android:2c24226c001234c58c87af',
    messagingSenderId: '868959012606',
    projectId: 'jaldi-app-cb1',
    storageBucket: 'jaldi-app-cb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDroyJGUDZAqFmu0BseIkEO14-TA9pr4JI',
    appId: '1:868959012606:ios:5033f55cdd97eb168c87af',
    messagingSenderId: '868959012606',
    projectId: 'jaldi-app-cb1',
    storageBucket: 'jaldi-app-cb1.firebasestorage.app',
    iosBundleId: 'com.example.sadakSevaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDroyJGUDZAqFmu0BseIkEO14-TA9pr4JI',
    appId: '1:868959012606:ios:5033f55cdd97eb168c87af',
    messagingSenderId: '868959012606',
    projectId: 'jaldi-app-cb1',
    storageBucket: 'jaldi-app-cb1.firebasestorage.app',
    iosBundleId: 'com.example.sadakSevaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9nk2QHziQZu-BQ0kupiG6Z-2ce4XbiNA',
    appId: '1:868959012606:web:4dfe07606952f4c98c87af',
    messagingSenderId: '868959012606',
    projectId: 'jaldi-app-cb1',
    authDomain: 'jaldi-app-cb1.firebaseapp.com',
    storageBucket: 'jaldi-app-cb1.firebasestorage.app',
  );
}
